INSERT INTO services (id, service_name, pictureurl) VALUES (123, 'House Cleaners', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (234, 'Interior Painters', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (345, 'Handymen', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (456, 'Photographers', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (567, 'Makeup Artists', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (678, 'Dog Groomers', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (789, 'Dog Trainers', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (890, 'Pet Sitters', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (321, 'Math Tutoring', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (432, 'Piano Lessons', 'https://i.imgur.com/ZblVXN7.jpg');
INSERT INTO services (id, service_name, pictureurl) VALUES (543, 'Personal Training', 'https://i.imgur.com/ZblVXN7.jpg');